'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getAdminOrganization, updateAdminOrganization, type OrganizationAdminProfile } from '@/lib/api';
export default function OrganizationProfilePage(){const router=useRouter();const [data,setData]=useState<OrganizationAdminProfile|null>(null);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
 useEffect(()=>{const t=localStorage.getItem('finplan_token');if(!t){router.replace('/login');return;}void getAdminOrganization(t).then(setData).catch(e=>setError(e.message));},[router]);
 async function submit(e:FormEvent){e.preventDefault();const t=localStorage.getItem('finplan_token');if(!t||!data)return;try{setData(await updateAdminOrganization(t,{legal_name:data.legal_name,trade_name:data.trade_name,organization_type:data.organization_type,email:data.email,phone:data.phone,website:data.website,registration_number:data.registration_number,pan_number:data.pan_number,gst_number:data.gst_number,financial_year_start:data.financial_year_start,default_currency_code:data.default_currency_code,timezone:data.timezone}));setSaved(true);}catch(reason){setError(reason instanceof Error?reason.message:'Update failed');}}
 if(!data)return <main className="min-h-screen bg-bone p-12 text-ash">{error||'Loading…'}</main>;
 const field=(key:keyof OrganizationAdminProfile,label:string)=><label className="block text-sm"><span className="mb-2 block">{label}</span><input value={String(data[key]??'')} onChange={e=>setData({...data,[key]:e.target.value})} className="w-full border border-line bg-bone px-4 py-3"/></label>;
 return <main className="min-h-screen bg-bone px-6 py-12 text-obsidian"><form onSubmit={submit} className="mx-auto max-w-3xl space-y-6"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-ash">Organization administration</p><h1 className="mt-2 text-4xl font-semibold">Edit Organization</h1><p className="mt-2 text-sm text-ash">{data.organization_code} · Update the fields below and save your changes.</p></div>{error&&<p className="text-red-700">{error}</p>}<div className="grid gap-5 border border-line bg-white p-6 md:grid-cols-2">{field('legal_name','Legal name')}{field('trade_name','Organization name')}{field('organization_type','Organization type')}{field('registration_number','Registration number')}{field('pan_number','PAN')}{field('gst_number','GST')}{field('email','Primary email')}{field('phone','Primary phone')}{field('website','Website')}{field('financial_year_start','Financial year start (MM-DD)')}{field('default_currency_code','Default currency')}{field('timezone','Timezone')}</div><button className="bg-obsidian px-5 py-3 text-sm text-bone">Save organization</button>{saved&&<span className="ml-4 text-sm text-green-700">Saved</span>}</form></main>;
}
