'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { getAdminEmployee, getAdminEmployeeHistory, listAdminBranches, listAdminDepartments, listAdminDesignations, listAdminEmployees, updateAdminEmployee, type AdminBranch, type AdminDepartment, type AdminDesignation, type AdminEmployee, type AdminEmployeeHistory } from '@/lib/api';
import EmployeeAccessPanel from '@/components/admin/EmployeeAccessPanel';
import EmployeeAssignmentsPanel from '@/components/admin/EmployeeAssignmentsPanel';
import EmployeeActivityPanel from '@/components/admin/EmployeeActivityPanel';

export default function EmployeeDetailPage(){
  const params=useParams<{id:string}>();const router=useRouter();const id=Number(params.id);const [employee,setEmployee]=useState<AdminEmployee|null>(null);const [history,setHistory]=useState<AdminEmployeeHistory|null>(null);const [branches,setBranches]=useState<AdminBranch[]>([]);const [departments,setDepartments]=useState<AdminDepartment[]>([]);const [designations,setDesignations]=useState<AdminDesignation[]>([]);const [employees,setEmployees]=useState<AdminEmployee[]>([]);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
  const load=useCallback(async()=>{const token=localStorage.getItem('finplan_token');if(!token){router.replace('/login');return;}try{const [item,h,b,d,g,e]=await Promise.all([getAdminEmployee(token,id),getAdminEmployeeHistory(token,id),listAdminBranches(token),listAdminDepartments(token),listAdminDesignations(token),listAdminEmployees(token)]);setEmployee(item);setHistory(h);setBranches(b.filter(x=>x.is_active));setDepartments(d.filter(x=>x.is_active));setDesignations(g.filter(x=>x.is_active));setEmployees(e.filter(x=>x.is_active&&x.id!==id));}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load employee');}},[id,router]);
  useEffect(()=>{void load();},[load]);
  async function submit(event:FormEvent){event.preventDefault();const token=localStorage.getItem('finplan_token');if(!token||!employee)return;setError('');setSaved(false);try{const {first_name,middle_name,last_name,display_name,personal_email,mobile_number,date_of_birth,branch_id,department_id,designation_id,employment_type,employment_status,joining_date,confirmation_date,official_email,official_mobile,reporting_manager_employee_id,remarks}=employee;setEmployee(await updateAdminEmployee(token,id,{first_name,middle_name,last_name,display_name,personal_email,mobile_number,date_of_birth,branch_id,department_id,designation_id,employment_type,employment_status,joining_date,confirmation_date,official_email:official_email||undefined,official_mobile,reporting_manager_employee_id,remarks}));setSaved(true);await load();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save employee');}}
  if(!employee)return <main className="min-h-screen bg-bone p-12 text-ash">{error||'Loading…'}</main>;
  const input='w-full border border-line bg-bone px-3 py-2 text-sm';const set=(key:keyof AdminEmployee,value:unknown)=>setEmployee(current=>current?{...current,[key]:value}:current);
  return <main className="min-h-screen bg-bone px-6 py-12 text-obsidian"><section className="mx-auto max-w-5xl space-y-6"><div><Link href="/admin/organization/employees" className="text-sm text-ash underline">← Employees</Link><h1 className="mt-3 text-4xl font-semibold">{employee.display_name}</h1><p className="mt-1 text-sm text-ash">{employee.employee_code} · {employee.employment_status}</p></div>{error&&<div className="border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
    <nav className="flex gap-1 overflow-x-auto border border-line bg-white p-2 text-sm">{[['Overview','overview'],['Reporting','reporting'],['Access','access'],['Assigned Clients','assignments'],['Activity','activity']].map(([label,target])=><a key={target} href={`#${target}`} className="whitespace-nowrap px-3 py-2 text-ash hover:bg-bone-deep hover:text-obsidian">{label}</a>)}</nav>
    <form id="overview" onSubmit={submit} className="scroll-mt-24 grid gap-5 border border-line bg-white p-6 md:grid-cols-2">
      <label className="text-sm">First name<input required value={employee.first_name||''} onChange={e=>set('first_name',e.target.value)} className={input}/></label><label className="text-sm">Last name<input value={employee.last_name||''} onChange={e=>set('last_name',e.target.value)} className={input}/></label>
      <label className="text-sm">Display name<input required value={employee.display_name} onChange={e=>set('display_name',e.target.value)} className={input}/></label><label className="text-sm">Official email<input required type="email" value={employee.official_email||''} onChange={e=>set('official_email',e.target.value)} className={input}/></label>
      <label className="text-sm">Branch<select value={employee.branch_id} onChange={e=>set('branch_id',Number(e.target.value))} className={input}>{branches.map(x=><option key={x.id} value={x.id}>{x.branch_name}</option>)}</select></label><label className="text-sm">Department<select value={employee.department_id} onChange={e=>set('department_id',Number(e.target.value))} className={input}>{departments.filter(x=>x.branch_id===employee.branch_id).map(x=><option key={x.id} value={x.id}>{x.department_name}</option>)}</select></label>
      <label className="text-sm">Designation<select value={employee.designation_id} onChange={e=>set('designation_id',Number(e.target.value))} className={input}>{designations.map(x=><option key={x.id} value={x.id}>{x.designation_name}</option>)}</select></label><label className="text-sm">Reporting manager<select value={employee.reporting_manager_employee_id||''} onChange={e=>set('reporting_manager_employee_id',e.target.value?Number(e.target.value):null)} className={input}><option value="">No reporting manager</option>{employees.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label>
      <label className="text-sm">Employment type<select value={employee.employment_type} onChange={e=>set('employment_type',e.target.value)} className={input}><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="CONTRACT">Contract</option><option value="INTERN">Intern</option><option value="CONSULTANT">Consultant</option></select></label><label className="text-sm">Status<select value={employee.employment_status} onChange={e=>set('employment_status',e.target.value)} className={input}><option value="ACTIVE">Active</option><option value="ON_LEAVE">On leave</option><option value="RELIEVED">Relieved</option><option value="INACTIVE">Inactive</option></select></label>
      <label className="text-sm md:col-span-2">Remarks<textarea value={employee.remarks||''} onChange={e=>set('remarks',e.target.value)} className={input}/></label><div><button className="bg-obsidian px-5 py-3 text-sm text-bone">Save employee</button>{saved&&<span className="ml-3 text-sm text-green-700">Saved</span>}</div>
    </form>
    <section id="reporting" className="scroll-mt-24 border border-line bg-white p-6"><h2 className="text-xl font-semibold">Employment and reporting history</h2><div className="mt-4 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{(['branches','departments','designations','reporting'] as const).map(kind=><div key={kind}><h3 className="mb-2 text-xs uppercase tracking-wider text-ash">{kind}</h3>{history?.[kind].map(row=><p key={row.id} className="border-t border-line py-2 text-sm">{row.effective_from||'Unknown'} → {row.effective_to||'Current'}<br/><span className="text-ash">Record #{row.branch_id||row.department_id||row.designation_id||row.manager_employee_id}</span></p>)}</div>)}</div></section>
    <div id="access" className="scroll-mt-24"><EmployeeAccessPanel employeeId={employee.id}/></div>
    <div id="assignments" className="scroll-mt-24"><EmployeeAssignmentsPanel employeeId={employee.id}/></div>
    <div id="activity" className="scroll-mt-24"><EmployeeActivityPanel employeeId={employee.id}/></div>
  </section></main>;
}
