"""Allowed values for new group memberships; historical values remain readable."""

HOUSEHOLD_RELATIONSHIPS = (
    "SELF", "SPOUSE", "SON", "DAUGHTER", "FATHER", "MOTHER", "BROTHER",
    "SISTER", "GRANDFATHER", "GRANDMOTHER", "DEPENDENT", "MEMBER", "OTHER",
)

GROUP_RELATIONSHIPS = {
    "HOUSEHOLD": HOUSEHOLD_RELATIONSHIPS,
    "FAMILY": HOUSEHOLD_RELATIONSHIPS,
    "BUSINESS": ("DIRECTOR", "OWNER", "PARTNER", "SHAREHOLDER", "EMPLOYEE", "MEMBER", "OTHER"),
    "INVESTMENT": ("INVESTOR", "BENEFICIAL_OWNER", "MEMBER", "OTHER"),
    "TRUST": ("TRUSTEE", "SETTLOR", "BENEFICIARY", "MEMBER", "OTHER"),
    "HUF": ("KARTA", "MEMBER", "OTHER"),
    "OTHER": ("MEMBER", "OTHER"),
}
