import { ColumnDef } from "@tanstack/react-table";

import {
  StatusColumn,
  DateColumn,
  ActionColumn,
} from "@/components/data-table";

import { reportActions } from "./report.actions";
import { Report } from "./report.types";

export const reportColumns: ColumnDef<Report>[] = [
  {
    accessorKey: "name",
    header: "Report",
  },
  {
    accessorKey: "type",
    header: "Type",
  },
  {
    accessorKey: "format",
    header: "Format",
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
  },
  {
    accessorKey: "dateRange",
    header: "Date Range",
  },
  {
    accessorKey: "fileSize",
    header: "File Size",
  },
  {
    accessorKey: "createdAt",
    header: "Generated On",
    cell: ({ row }) =>
      row.original.createdAt ? (
        <DateColumn value={row.original.createdAt} />
      ) : (
        "—"
      ),
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => <StatusColumn value={row.original.status} />,
  },
  {
    id: "actions",
    cell: ({ row }) => (
      <ActionColumn row={row.original} actions={reportActions} />
    ),
  },
];