'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { createAdminEmployeeAssignment, endAdminEmployeeAssignment, getClients, getGroups, listAdminBranches, listAdminEmployeeAssignments, type AdminAssignmentEntityType, type AdminBranch, type AdminEmployeeAssignment, type Client, type Group } from '@/lib/api';

export default function EmployeeAssignmentsPanel({employeeId}:{employeeId:number}){
  const [items,setItems]=useState<AdminEmployeeAssignment[]>([]);const [clients,setClients]=useState<Client[]>([]);const [groups,setGroups]=useState<Group[]>([]);const [branches,setBranches]=useState<AdminBranch[]>([]);
  const [type,setType]=useState<AdminAssignmentEntityType>('CUSTOMER');const [entityId,setEntityId]=useState('');const [start,setStart]=useState(new Date().toISOString().slice(0,10));const [remarks,setRemarks]=useState('');const [error,setError]=useState('');
  const token=()=>localStorage.getItem('finplan_token')||'';
  const load=useCallback(async()=>{try{const t=token();const [a,c,g,b]=await Promise.all([listAdminEmployeeAssignments(t,employeeId),getClients(t,{page_size:100}),getGroups(t),listAdminBranches(t)]);setItems(a);setClients(c.clients);setGroups(g.groups);setBranches(b.filter(x=>x.is_active));}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load assignments');}},[employeeId]);
  useEffect(()=>{void load();},[load]);
  const options=useMemo(()=>type==='CUSTOMER'?clients.map(x=>({id:x.id,name:`${x.first_name} ${x.last_name}`.trim()})):type==='CUSTOMER_GROUP'?groups.filter(x=>x.is_active).map(x=>({id:x.id,name:x.group_name})):branches.map(x=>({id:x.id,name:x.branch_name})),[type,clients,groups,branches]);
  async function submit(event:FormEvent){event.preventDefault();setError('');try{await createAdminEmployeeAssignment(token(),employeeId,{entity_type:type,entity_id:Number(entityId),effective_from:start,remarks:remarks||null});setEntityId('');setRemarks('');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create assignment');}}
  async function end(row:AdminEmployeeAssignment){setError('');try{await endAdminEmployeeAssignment(token(),employeeId,row.id,new Date().toISOString().slice(0,10));await load();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to end assignment');}}
  return <section className="space-y-5 border border-line bg-white p-6"><div><h2 className="text-xl font-semibold">Assignments</h2><p className="mt-1 text-sm text-ash">Client assignments apply directly. Group and branch assignments include active members of the matching group scope.</p></div>{error&&<div className="border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
    <form onSubmit={submit} className="grid gap-3 bg-bone-deep p-4 md:grid-cols-4"><select value={type} onChange={e=>{setType(e.target.value as AdminAssignmentEntityType);setEntityId('');}} className="border border-line bg-bone px-3 py-2"><option value="CUSTOMER">Client</option><option value="CUSTOMER_GROUP">Group</option><option value="BRANCH">Branch</option></select><select required value={entityId} onChange={e=>setEntityId(e.target.value)} className="border border-line bg-bone px-3 py-2"><option value="">Select target</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required type="date" value={start} onChange={e=>setStart(e.target.value)} className="border border-line bg-bone px-3 py-2"/><button className="bg-obsidian px-4 py-2 text-sm text-bone">Add assignment</button><input value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Remarks (optional)" className="border border-line bg-bone px-3 py-2 md:col-span-4"/></form>
    <div className="overflow-x-auto border border-line"><table className="w-full text-left text-sm"><thead className="bg-bone-deep text-xs uppercase tracking-wider text-ash"><tr><th className="p-3">Scope</th><th className="p-3">Target</th><th className="p-3">Period</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{items.map(row=><tr key={row.id} className="border-t border-line"><td className="p-3">{row.entity_type.replace(/_/g,' ')}</td><td className="p-3">{row.entity_name}</td><td className="p-3">{row.effective_from} → {row.effective_to||'Current'}</td><td className="p-3">{row.is_active&&!row.effective_to?'Active':'Ended'}</td><td className="p-3">{row.is_active&&!row.effective_to&&<button onClick={()=>void end(row)} className="underline">End</button>}</td></tr>)}</tbody></table></div>
  </section>;
}
